services:
  mysql-db:
    image: docker.io/bitnami/mysql:8.4
    container_name: mysql-db
    env_file: .env
    environment:
      ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    networks:
      - spring-net
    volumes:
      - mysql-data:/bitnami/mysql/data
      - ./mysql-init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/mysql/healthcheck.sh"]
      interval: 15s
      timeout: 5s
      retries: 6

  commercify:
    image: ghcr.io/zenfulcode/commercify:dev
    env_file: .env
    container_name: commercify-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - STRIPE_TEST_SECRET=${STRIPE_TEST_SECRET}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - spring-net

networks:
  spring-net:
    driver: bridge

volumes:
  mysql-data:
    driver: local
