import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";

// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
    // <html lang="en">
    //   <body className={geistMono.className}>
    //     <div className="flex h-screen bg-gray-100">
    //       <Sidebar />
    //       <div className="flex-1 overflow-auto">
    //         {children}
    //       </div>
    //     </div>
    //   </body>
    // </html>
  );
}
